apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-xetf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-xetf
    app.kubernetes.io/part-of: pt-test-app-50
  name: devfile-sample-xetf
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-xetf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-xetf
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/lpardo-tenant/pt-test-app-50/devfile-sample-xetf@sha256:0be193fda3bbc00beda622ae26c3f1943585c9b47c660a6854de609428903cbf
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
